apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: johny4473/eureka-server:latest # Cambia a la etiqueta correcta si no es `latest`
        ports:
        - containerPort: 8761 # Cambia al puerto expuesto por la imagen

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: 80        # Puerto que expone el servicio dentro del clúster
    targetPort: 8761 # Puerto del contenedor
  type: ClusterIP    # Cambia a LoadBalancer si deseas exponerlo públicamente
