spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
