version: "3.8"

services:
  api-gateway:
    build:
      context: ./gateway  # Ruta donde se encuentra el Dockerfile del API Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Puerto del API Gateway
    depends_on:
      - user-service
      - book-service
      - loan-service
      - reservation-service
    networks:
      - biblioteca-network

  user-service:
    build:
      context: ./backend/user-service  # Ruta donde se encuentra el Dockerfile del user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Puerto del user-service
    networks:
      - biblioteca-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin1234

  book-service:
    build:
      context: ./backend/book-service  # Ruta donde se encuentra el Dockerfile del book-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Puerto del book-service
    networks:
      - biblioteca-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/book_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin1234

  loan-service:
    build:
      context: ./backend/loan-service  # Ruta donde se encuentra el Dockerfile del loan-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"  # Puerto del loan-service
    networks:
      - biblioteca-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/loan_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin1234

  reservation-service:
    build:
      context: ./backend/reservation-service  # Ruta donde se encuentra el Dockerfile del reservation-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"  # Puerto del reservation-service
    networks:
      - biblioteca-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reservation_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin1234

  db:
    image: postgres:15  # Imagen de PostgreSQL
    container_name: biblioteca_db
    ports:
      - "5432:5432"  # Puerto del servicio de base de datos
    networks:
      - biblioteca-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volumen para persistir datos

networks:
  biblioteca-network:  # Red compartida entre los servicios

volumes:
  postgres-data:  # Volumen para persistencia de la base de datos
